name: blockchain_sdk_example
description: Example for the Blockchain SDK
version: 1.0.0
homepage: https://twitter.com/jbdtky

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  blockchain_sdk:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter