name: blockchain_sdk
description: A dart package used for blockchain related project
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  crypto: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter